
name: Directory Bruteforce

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # Runs every day at 4 PM UTC

jobs:
  directory-bruteforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ffuf
        run: |
          sudo apt-get update
          sudo apt-get install -y ffuf

      - name: Run ffuf to find directories
        run: |
          cat scan001.txt | while read subdomain; do
            ffuf -w directorys1.txt -u http://$subdomain/FUZZ -o temp_result.txt -of csv
            cat temp_result.txt | grep ",200," | cut -d',' -f1 >> directorys.txt
          done

      - name: Upload directorys.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: discovered-directories
          path: directorys.txt
